### ISSUE TITLE
M5 - A2 - Develop benchmarking methods and graphics.

### ISSUE THREAD

**Issue by renovus** [Renovus-Tech/solarec-react#1]
This will help users compare their production to other similar plants with similar radiation levels

Test features with users, sampling whether alerts work properly with in-depth fault analysis in 90% of tests

**Comment by nbartesaghi** [comment]
As result of the analyses, a new section of the Overview page was decided to be done, as described at: #12

**Comment by nbartesaghi** [comment]
As result of the analyse, a new section of the Overview page was decided to be done, as described at: #12
