### ISSUE TITLE
M7 - A1 - User testing (Product/UX/UI)

### ISSUE THREAD

**Issue by renovus** [Renovus-Tech/solarec-react#2]
Ensure that the platform is not only user-friendly but also intuitively navigable, with information presented in a clear and concise manner, facilitating effortless comprehension.

Conduct thorough usability testing with a diverse sample of users, aiming for a minimum of 25 participants at this developmental stage. Assess their interactions with the platform to ascertain its ease of use and the perceived value of its features. A target benchmark of 75% user satisfaction is recommended, indicating that the platform effectively meets the needs and expectations of the majority of its intended audience.

**Comment by pferrariuy** [comment]
The feedback gathered from small businesses during the testing phase of the app primarily revolves around their experiences with the various screens currently under development. 

They offer valuable insights into which features they perceive as the most useful or relevant to their needs and objectives. 

By articulating their preferences and providing constructive commentary, these businesses contribute significantly to the iterative refinement process, ensuring that the final product aligns closely with their operational requirements and enhances their overall user experience.

**Comment by nbartesaghi** [comment]
Following the links to the issues/commits related to the features/changes made to the app:

- Map of the location:
https://github.com/Renovus-Tech/solarec-react/issues/5

- Tones of CO2 in the overview page:
https://github.com/Renovus-Tech/solarec-react/commit/d1a242ba055345162ace94d135ad8cbd00492024

- Support for multiple languages:
https://github.com/Renovus-Tech/solarec-react/issues/8

- Improvements to user settings:
https://github.com/Renovus-Tech/solarec-react/commit/c63cabfa12ce71a9663bd1c220de78f81370a5a1
