### ISSUE TITLE
Execution of user testing

### ISSUE THREAD

**Issue by pferrariuy** [Renovus-Tech/solarec-react#22]
List of test:

Comments will include findings.

**Comment by nbartesaghi** [comment]
Along the development of the different modules and functionalities the application was tested, first by an internal tester to detect errors, and then by other users to detect opportunities of improving the user interface as well as adding new functionalities or modifying existing ones.
All feedbacks were taken into account and many changes and fixes on the platform were derived from these testing instances.

**Comment by nbartesaghi** [comment]
Along the development of the different modules and functionalities the application was tested, first by an internal tester to detect errors, and then by other users to detect opportunities of improving the user interface as well as adding new functionalities or modifying existing ones.
All feedbacks were taken into account and many changes and fixes on the platform were derived from these testing instances.
